version: 2

jobs:
  macos:
    macos:
      xcode: "9.0"
    steps:
      - run: brew install vapor/tap/vapor vapor/tap/cmysql
      - run: brew services start mysql
      - checkout
      - run: swift build
      - run: swift test

  linux:
    docker:
      - image: swift:4.0
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: vapor_test
    steps:
      - run: apt-get update
      - run: apt-get install -y libssl-dev
      - checkout
      - run: swift build
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-3
