version: 2

jobs:
  macos:
    macos:
      xcode: "9.0"
    steps:
      - run: brew install vapor/tap/vapor vapor/tap/cmysql
      - run: brew services start mysql
      - checkout
      - run: swift build
      - run: swift test

  linux:
    docker:
      - image: swift:4.0
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - run: eval "$(curl -sL https://apt.vapor.sh)"
      - run: apt-get install cmysql ctls
      - checkout
      - run: swift build
      - run: swift test

  # 3.1 backward compat checks

  linux-3:
    docker:
      - image: swift:3.1
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - run: eval "$(curl -sL https://apt.vapor.sh)"
      - run: apt-get install cmysql ctls
      - checkout
      - run: swift build
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
      - macos
      - linux
      - linux-3